module.exports = {
    FULL_ACCESS:'FULL_ACCESS',
    VIEW_ACCESS:'VIEW_ACCESS',
    NO_ACCESS:'NO_ACCESS',
    ALL_REQUESTS:'ALL_REQUESTS',
    CREATIVE_REQUESTS:'CREATIVE_REQUESTS',
    CAMPAIGN_LEVEL:'CAMPAIGN_LEVEL',
    MANAGE_WALLET:'MANAGE_WALLET',
    COMPREHENSIVE_ACCESS:'COMPREHENSIVE_ACCESS'
}