module.exports = {
    AD_INVENTORY_PLACEMENTS:'AD_INVENTORY_PLACEMENTS',
    AUDIENCE_KEYS_VALUES:'AUDIENCE_KEYS_VALUES',
    ALL_PUBLISHER_CAMPAIGNS:'ALL_PUBLISHER_CAMPAIGNS',
    ALL_ADVERTISER_CAMPAIGNS:'ALL_ADVERTISER_CAMPAIGNS',
    CREATIVE_TEMPLATE:'CREATIVE_TEMPLATE',
    REPORT_GENERATION:'REPORT_GENERATION'   ,
    ADVERTISER_MANAGEMENT:'ADVERTISER_MANAGEMENT',
    ACCOUNT_SETUP:'ACCOUNT_SETUP',
    USER_MANAGEMENT:'USER_MANAGEMENT',
    APPROVAL_REQUESTS:'APPROVAL_REQUESTS',
    WALLET:'WALLET',
    INSIGHT_DASHBOARD:'INSIGHT_DASHBOARD',
    PUBLIC_API_ACCESS:'PUBLIC_API_ACCESS',
    YIELD_MANAGEMENT:'YIELD_MANAGEMENT',
    OFFSITE_INTEGRATIONS:'OFFSITE_INTEGRATIONS',
    OFFSITE_CAMPAIGNS:'OFFSITE_CAMPAIGNS'
}